[package]
name = "plotsweep"
version = "0.1.0"
authors = ["Mike Walters <mike@flomp.net>"]
edition = "2018"

[dependencies]
chrono = "0.4"
clap = "2"
colorous = "1.0"
csv = "1.1"
lazy_static = "1.4"
plotters = "0.3"
serde = { version = "1", features = ["derive"] }
